const assignments = {
  "csc301-lab4": {
    id: "csc301-lab4",
    status: "pending",
    course: "CSC 301",
    title: "Lab 4: Implementation of Dijkstra's Algorithm",
    subject: "Advanced Algorithms",
    postedBy: "Dr. Yusuf Muhammad",
    description:
      "Complete the implementation of Dijkstra's algorithm for finding the shortest path in a weighted graph.",
    requirements: [
      "Implement the algorithm using an adjacency list.",
      "Handle disconnected graphs and unreachable nodes.",
      "Include a short explanation of the time complexity.",
    ],
    note: "Submit your source code and a brief README with sample output.",
    maxScore: 20,
    dueDate: "Today, 11:59 PM",
    timeRemaining: "Due in 6 hours",
    materials: [
      { name: "lab4-starter-code.zip", size: "48 KB", type: "code" },
      { name: "lab4-instructions.pdf", size: "312 KB", type: "document" },
    ],
  },
  "csc305-a2": {
    id: "csc305-a2",
    status: "pending",
    course: "CSC 305",
    title: "Assignment 2: Shell Scripting & Automation",
    subject: "Systems Administration",
    postedBy: "Prof. Hauwa Bello",
    description:
      "Write a shell script that automates the backup process of a specific directory to a remote server.",
    requirements: [
      "Accept the source directory as a command-line argument.",
      "Create timestamped backup archives.",
      "Document the setup and execution steps.",
    ],
    maxScore: 25,
    dueDate: "Thursday, 2:00 PM",
    timeRemaining: "Due in 3 days",
    materials: [
      { name: "backup-requirements.pdf", size: "220 KB", type: "document" },
      { name: "sample-config.sh", size: "6 KB", type: "code" },
    ],
  },
  "csc309-paper": {
    id: "csc309-paper",
    status: "pending",
    course: "CSC 309",
    title: "Research Paper: Ethical Hacking & Security",
    subject: "Cybersecurity",
    postedBy: "Dr. Yusuf Muhammad",
    description:
      "Write a comprehensive research paper on modern penetration testing methodologies and ethical considerations.",
    requirements: [
      "Compare at least two penetration testing methodologies.",
      "Use credible academic and industry sources.",
      "Discuss the ethical responsibilities of security professionals.",
    ],
    maxScore: 30,
    dueDate: "Friday, 11:59 PM",
    timeRemaining: "Due in 4 days",
    materials: [
      { name: "paper-guidelines.pdf", size: "180 KB", type: "document" },
    ],
  },
  "csc307-proposal": {
    id: "csc307-proposal",
    status: "graded",
    course: "CSC307",
    title: "Project Proposal: SaaS Architecture",
    subject: "Software Architecture",
    gradedDate: "Aug 15, 2024",
    studentFirstName: "David",
    score: "18",
    maxScore: "20",
    gradeComment: "A clear and well-structured proposal with strong architectural reasoning.",
    rankBadge: "Top 10% of class",
    submittedBadge: "Submitted on time",
    instructor: {
      name: "Dr. Yusuf Muhammad",
      avatar: "/avatar-placeholder.svg",
      comment: "Your service boundaries and scaling considerations were especially strong.",
      timestamp: "Aug 15, 2024 at 3:42 PM",
    },
    rubric: [
      { label: "Architecture", description: "System structure and boundaries", score: "7/8" },
      { label: "Technical depth", description: "Tradeoffs and implementation detail", score: "6/6" },
      { label: "Clarity", description: "Organization and communication", score: "5/6" },
    ],
    submission: {
      filename: "saas-architecture-proposal.pdf",
      date: "Aug 14, 2024",
      id: "SUB-307-0814",
      plagiarism: "2%",
    },
    nextSteps: "Use this architecture as the foundation for your implementation milestone.",
  },
  "csc311-quiz": {
    id: "csc311-quiz",
    status: "graded",
    course: "CSC311",
    title: "Mid-Semester Quiz: Database Systems",
    subject: "Database Systems",
    gradedDate: "Aug 12, 2024",
    studentFirstName: "David",
    score: "9.5",
    maxScore: "10",
    gradeComment: "Excellent understanding of relational modeling and query optimization.",
    rankBadge: "Top 15% of class",
    submittedBadge: "Submitted on time",
    instructor: {
      name: "Prof. Hauwa Bello",
      avatar: "/avatar-placeholder.svg",
      comment: "Your query plans were accurate and your explanations were concise.",
      timestamp: "Aug 12, 2024 at 10:15 AM",
    },
    rubric: [
      { label: "Query design", description: "Correctness and efficiency", score: "4/4" },
      { label: "Data modeling", description: "Schema and relationships", score: "3/3" },
      { label: "Explanations", description: "Reasoning and clarity", score: "2.5/3" },
    ],
    submission: {
      filename: "database-systems-quiz.pdf",
      date: "Aug 12, 2024",
      id: "SUB-311-0812",
      plagiarism: "0%",
    },
    nextSteps: "Review the feedback before starting the final database project.",
  },
};

export function getAssignment(id) {
  return assignments[id] ?? null;
}
