import { SHUTTLE_STATUS, BOOKING_STATUS, RIDE_STATUS } from "./rideStatus";

export const drivers = [
  {
    id: "drv-1",
    name: "Malam Ibrahim Sule",
    phone: "+2348035550192",
    vehicleNumber: "KN-234-XA",
    avatar: "/avatar-placeholder.svg",
    rating: 4.8,
  },
  {
    id: "drv-2",
    name: "Hajiya Amina Yusuf",
    phone: "+2348062104471",
    vehicleNumber: "KN-118-BB",
    avatar: "/avatar-placeholder.svg",
    rating: 4.9,
  },
  {
    id: "drv-3",
    name: "Musa Abdullahi",
    phone: "+2347019923305",
    vehicleNumber: "KN-077-KC",
    avatar: "/avatar-placeholder.svg",
    rating: 4.6,
  },
];

export const routes = [
  {
    id: "route-hostel-main",
    name: "Hostel → Main Campus",
    status: "active",
    nextShuttleEtaMinutes: 4,
    frequencyMinutes: 10,
    availableSeats: 18,
    fare: 150,
    stops: [
      { id: "stop-hostel-gate", name: "Hostel Gate", order: 1 },
      { id: "stop-junction", name: "Central Junction", order: 2 },
      { id: "stop-fac-computing", name: "Faculty of Computing", order: 3 },
      { id: "stop-main-campus", name: "Main Campus Gate", order: 4 },
    ],
  },
  {
    id: "route-science-gateb",
    name: "Faculty of Science → Gate B",
    status: "active",
    nextShuttleEtaMinutes: 8,
    frequencyMinutes: 15,
    availableSeats: 6,
    fare: 100,
    stops: [
      { id: "stop-fac-science", name: "Faculty of Science", order: 1 },
      { id: "stop-library", name: "Main Library", order: 2 },
      { id: "stop-gate-b", name: "Gate B", order: 3 },
    ],
  },
  {
    id: "route-medical-lt04",
    name: "Medical Center → LT-04",
    status: "delayed",
    nextShuttleEtaMinutes: 15,
    frequencyMinutes: 20,
    availableSeats: 0,
    fare: 100,
    stops: [
      { id: "stop-medical", name: "Medical Center", order: 1 },
      { id: "stop-fac-arts", name: "Faculty of Arts", order: 2 },
      { id: "stop-lt04", name: "LT-04", order: 3 },
    ],
  },
];

export const shuttles = [
  {
    id: "shuttle-gate-a",
    name: "Gate A Shuttle",
    routeId: "route-hostel-main",
    destination: "Main Library",
    nextStop: "Main Library",
    status: SHUTTLE_STATUS.ARRIVING,
    etaMinutes: 3,
    seatsAvailable: 12,
    totalSeats: 20,
    fare: 150,
    driverId: "drv-1",
    position: { top: "42%", left: "48%" },
  },
  {
    id: "shuttle-hostel-express",
    name: "Hostel Express",
    routeId: "route-hostel-main",
    destination: "Main Campus",
    nextStop: "Central Junction",
    status: SHUTTLE_STATUS.AWAY,
    etaMinutes: 8,
    seatsAvailable: 8,
    totalSeats: 20,
    fare: 150,
    driverId: "drv-2",
    position: { top: "58%", left: "30%" },
  },
  {
    id: "shuttle-science-lt",
    name: "Science LT Route",
    routeId: "route-science-gateb",
    destination: "Gate B",
    nextStop: "Gate B",
    status: SHUTTLE_STATUS.FULL,
    etaMinutes: 15,
    seatsAvailable: 0,
    totalSeats: 18,
    fare: 100,
    driverId: "drv-3",
    position: { top: "25%", left: "65%" },
  },
  {
    id: "shuttle-medical",
    name: "Medical Center Shuttle",
    routeId: "route-medical-lt04",
    destination: "LT-04",
    nextStop: "Faculty of Arts",
    status: SHUTTLE_STATUS.DELAYED,
    etaMinutes: 15,
    seatsAvailable: 4,
    totalSeats: 18,
    fare: 100,
    driverId: "drv-3",
    position: { top: "70%", left: "70%" },
  },
  {
    id: "shuttle-night",
    name: "Night Loop Shuttle",
    routeId: "route-hostel-main",
    destination: "Hostel",
    nextStop: "—",
    status: SHUTTLE_STATUS.OFFLINE,
    etaMinutes: null,
    seatsAvailable: 0,
    totalSeats: 20,
    fare: 150,
    driverId: null,
    position: { top: "15%", left: "20%" },
  },
];

export const studentLocation = { top: "50%", left: "50%" };

export const initialBookings = [
  {
    id: "bk-1002",
    routeId: "route-hostel-main",
    routeName: "Hostel → Main Campus",
    shuttleId: "shuttle-gate-a",
    shuttleName: "Gate A Shuttle",
    date: "Today",
    departureTime: "4:30 PM",
    gate: "Gate A",
    seat: "12",
    fare: 150,
    status: BOOKING_STATUS.UPCOMING,
    rideStatus: RIDE_STATUS.APPROACHING,
    driverId: "drv-1",
    createdAt: "2026-09-05T10:00:00.000Z",
  },
  {
    id: "bk-0998",
    routeId: "route-science-gateb",
    routeName: "Faculty of Science → Gate B",
    shuttleId: "shuttle-science-lt",
    shuttleName: "Science LT Route",
    date: "Sep 3, 2026",
    departureTime: "1:15 PM",
    gate: "Gate B",
    seat: "6",
    fare: 100,
    status: BOOKING_STATUS.COMPLETED,
    rideStatus: RIDE_STATUS.COMPLETED,
    driverId: "drv-3",
    createdAt: "2026-09-03T13:15:00.000Z",
  },
  {
    id: "bk-0991",
    routeId: "route-medical-lt04",
    routeName: "Medical Center → LT-04",
    shuttleId: "shuttle-medical",
    shuttleName: "Medical Center Shuttle",
    date: "Sep 1, 2026",
    departureTime: "9:00 AM",
    gate: "Medical Center",
    seat: "3",
    fare: 100,
    status: BOOKING_STATUS.CANCELLED,
    rideStatus: RIDE_STATUS.APPROACHING,
    driverId: "drv-3",
    createdAt: "2026-09-01T09:00:00.000Z",
  },
];

export const initialWalletBalance = 4250;

export const initialTransactions = [
  { id: "txn-3001", type: "topup", amount: 2000, date: "Sep 2, 2026", description: "Wallet top-up via card" },
  { id: "txn-3000", type: "fare", amount: -100, date: "Sep 1, 2026", description: "Medical Center → LT-04 ride" },
  { id: "txn-2999", type: "fare", amount: -100, date: "Aug 30, 2026", description: "Faculty of Science → Gate B ride" },
  { id: "txn-2998", type: "topup", amount: 3000, date: "Aug 28, 2026", description: "Wallet top-up via bank transfer" },
];